# Generated by Django 5.2.17 on 2026-10-03 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('fish', 'Fish'), ('meat', 'Meat'), ('vegetarian', 'Vegetarian'), ('other', 'Other')], default='other', max_length=12, verbose_name='type')),
                ('recipe_url', models.URLField(blank=True, max_length=500, verbose_name='recipe link')),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='cooking time (min)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'dishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], default='dinner', max_length=10, verbose_name='meal')),
                ('leftovers', models.BooleanField(default=False, help_text='Eaten from leftovers; nothing to buy.')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned', to='meals.dish')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', '-slot', 'pk'],
            },
        ),
    ]
