# Generated by Django 5.2.17 on 2026-10-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('likes', models.TextField(blank=True, verbose_name='favourite foods')),
                ('dislikes', models.TextField(blank=True)),
                ('avoid', models.TextField(blank=True, verbose_name="won't eat")),
                ('allergies', models.TextField(blank=True, verbose_name='allergies & intolerances')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['kind', 'birth_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals_to_plan', models.TextField(blank=True, help_text='E.g. dinners Mon–Fri, lunch and dinner at the weekend.')),
                ('weekday_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='max. cooking time on weekdays (min)')),
                ('weekend_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='max. cooking time at the weekend (min)')),
                ('adventurousness', models.PositiveSmallIntegerField(blank=True, help_text='1 = only familiar meals, 10 = try anything.', null=True, verbose_name='how adventurous (1–10)')),
                ('leftovers', models.TextField(blank=True, help_text='E.g. welcome for weekend lunches.', verbose_name='leftovers')),
                ('cuisines', models.TextField(blank=True, verbose_name='favourite cuisines')),
                ('equipment', models.TextField(blank=True, verbose_name='cooking equipment')),
                ('shops', models.TextField(blank=True, verbose_name='where we shop')),
                ('priority', models.CharField(choices=[('balanced', 'Balanced'), ('price', 'Price'), ('convenience', 'Convenience'), ('quality', 'Quality'), ('waste', 'Less waste')], default='balanced', max_length=12, verbose_name='optimise for')),
                ('pantry', models.TextField(blank=True, help_text='Things we always have; left off the shopping list.', verbose_name='pantry staples')),
                ('notes', models.TextField(blank=True, verbose_name='anything else')),
            ],
            options={
                'verbose_name_plural': 'household',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-active', 'created_at'],
            },
        ),
    ]
