# Generated by Django 5.2.17 on 2026-10-03 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_familymember_household_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids', models.CharField(blank=True, choices=[('loved', '❤️ Loved it'), ('liked', '👍 Liked it'), ('okay', '😐 Okay'), ('disliked', "👎 Didn't like it")], max_length=10)),
                ('parents', models.CharField(blank=True, choices=[('loved', '❤️ Loved it'), ('liked', '👍 Liked it'), ('okay', '😐 Okay'), ('disliked', "👎 Didn't like it")], max_length=10)),
                ('reaction', models.CharField(blank=True, help_text='Who reacted badly to it, and how.', max_length=300, verbose_name='bad reaction')),
                ('notes', models.TextField(blank=True, help_text='E.g. too spicy for the kids, would make it again with less garlic.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='meals.plannedmeal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
