# Generated by Django 5.2.17 on 2026-10-03 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(help_text='Monday of the week.')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('vegetables', '🥕 Fruit & vegetables'), ('fish', '🐟 Fish'), ('meat', '🥩 Meat'), ('vegetarian', '🌱 Vegetarian protein'), ('dairy', '🧀 Dairy & eggs'), ('bakery', '🍞 Bread & bakery'), ('breakfast', '🥣 Breakfast & snacks'), ('pantry', '🫙 Pantry'), ('frozen', '❄️ Frozen'), ('speciality', '🥢 Asian / speciality shop'), ('other', '🛒 Other')], default='other', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, help_text='E.g. g, kg, ml, pcs, can, bunch.', max_length=20)),
                ('category', models.CharField(choices=[('vegetables', '🥕 Fruit & vegetables'), ('fish', '🐟 Fish'), ('meat', '🥩 Meat'), ('vegetarian', '🌱 Vegetarian protein'), ('dairy', '🧀 Dairy & eggs'), ('bakery', '🍞 Bread & bakery'), ('breakfast', '🥣 Breakfast & snacks'), ('pantry', '🫙 Pantry'), ('frozen', '❄️ Frozen'), ('speciality', '🥢 Asian / speciality shop'), ('other', '🛒 Other')], default='other', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.dish')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('key', models.CharField(max_length=120)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week', 'key'), name='unique_check_per_week')],
            },
        ),
    ]
