# Generated by Django 5.2.17 on 2026-10-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_extraitem_ingredient_shoppingcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
