# Generated by Django 5.2.17 on 2026-10-03 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_extraitem_removed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='servings',
            field=models.PositiveSmallIntegerField(default=4, help_text='How many portions the ingredient quantities are for.', verbose_name='portions'),
        ),
        migrations.AddField(
            model_name='household',
            name='usual_week',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannedmeal',
            name='eaters',
            field=models.ManyToManyField(blank=True, related_name='meals', to='meals.familymember', verbose_name='who eats'),
        ),
        migrations.AddField(
            model_name='plannedmeal',
            name='servings',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Including any to keep as leftovers. Empty: as many as the recipe makes.', null=True, verbose_name='portions to cook'),
        ),
        migrations.CreateModel(
            name='MenuRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(help_text='Monday of the week.')),
                ('slots', models.JSONField(default=list)),
                ('keep_existing', models.BooleanField(default=True, help_text='Keep meals that are already planned.')),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('running', 'Creating'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
