# Generated by Django 5.2.17 on 2026-10-03 20:39

from django.db import migrations


def texts_to_rules(apps, schema_editor):
    """Keep what was written in the removed household fields, as rules."""
    Household = apps.get_model("meals", "Household")
    Rule = apps.get_model("meals", "Rule")
    for household in Household.objects.all():
        for prefix, text in [
            ("Meals we plan: ", household.meals_to_plan),
            ("Leftovers: ", household.leftovers),
            ("", household.notes),
        ]:
            text = " ".join(text.split())
            if text:
                Rule.objects.create(text=(prefix + text)[:300])


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_dish_servings_household_usual_week_and_more'),
    ]

    operations = [
        migrations.RunPython(texts_to_rules, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='household',
            name='leftovers',
        ),
        migrations.RemoveField(
            model_name='household',
            name='meals_to_plan',
        ),
        migrations.RemoveField(
            model_name='household',
            name='notes',
        ),
    ]
