# Generated by Django 5.2.17 on 2026-10-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_household_texts_to_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='other_sites',
            field=models.CharField(choices=[('never', 'Never – only the sites above'), ('rarely', 'Rarely – about one recipe a week'), ('sometimes', 'Sometimes – about a third of the recipes'), ('often', 'Often – whenever another site has a better recipe')], default='sometimes', max_length=10, verbose_name='recipes from other websites'),
        ),
        migrations.AddField(
            model_name='household',
            name='recipe_sites',
            field=models.TextField(blank=True, help_text='One per line, e.g. bbcgoodfood.com. Searched first when creating a menu.', verbose_name='recipe websites'),
        ),
        migrations.AddField(
            model_name='menurequest',
            name='kind',
            field=models.CharField(choices=[('create', 'Create menu'), ('change', 'Change menu'), ('replace', 'Replace a dish')], default='create', max_length=10),
        ),
        migrations.AddField(
            model_name='menurequest',
            name='replacing',
            field=models.CharField(blank=True, help_text="Dish being replaced, for 'replace' requests.", max_length=200),
        ),
    ]
