# Generated by Django 5.2.17 on 2026-10-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_change_and_replace_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='other_sites',
            field=models.CharField(choices=[('never', 'Never – only the sources above'), ('rarely', 'Rarely – about one recipe a week'), ('sometimes', 'Sometimes – about a third of the recipes'), ('often', 'Often – whenever another site has a better recipe')], default='sometimes', max_length=10, verbose_name='recipes from other sources'),
        ),
        migrations.AlterField(
            model_name='household',
            name='recipe_sites',
            field=models.TextField(blank=True, help_text='One per line: websites (bbcgoodfood.com) or names (Jamie Oliver). Searched first when creating a menu.', verbose_name='recipe sources'),
        ),
    ]
