# Generated by Django 5.2.17 on 2026-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_recipe_sources_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='menurequest',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='cost (USD)'),
        ),
        migrations.AddField(
            model_name='menurequest',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='menurequest',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menurequest',
            name='response',
            field=models.TextField(blank=True, help_text="The AI's answer (save_menu arguments) as JSON."),
        ),
        migrations.AddField(
            model_name='menurequest',
            name='web_searches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
