# Generated by Django 5.2.17 on 2026-10-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_request_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='saved_at',
            field=models.DateTimeField(blank=True, help_text='When it was put in the binder.', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Not in the binder'), ('try', 'Want to try'), ('favourite', 'Favourite')], default='', max_length=10, verbose_name='binder'),
        ),
    ]
