# Generated by Django 5.2.17 on 2026-10-04 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_recipe_binder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='instructions',
            field=models.TextField(blank=True, help_text='The steps, one per line.', verbose_name='method'),
        ),
        migrations.AddField(
            model_name='dish',
            name='source',
            field=models.CharField(blank=True, help_text="Where it's from, e.g. BBC Good Food magazine, Oct 2026, p. 42.", max_length=200),
        ),
        migrations.CreateModel(
            name='RecipeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('running', 'Reading'), ('done', 'Ready to check'), ('failed', 'Failed'), ('saved', 'Saved')], default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict, help_text='What the AI read, before checking.')),
                ('error', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('web_searches', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='cost (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='meals.dish')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='meals.dish')),
                ('recipe_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='meals.recipeimport')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
