# Generated by Django 5.2.17 on 2026-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_recipe_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimport',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='recipe link'),
        ),
    ]
