# Generated by Django 5.2.17 on 2026-10-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_recipe_import_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='freezer',
            field=models.TextField(blank=True, help_text='Things always in the freezer.', verbose_name='freezer staples'),
        ),
    ]
