# Generated by Django 5.2.17 on 2026-10-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_freezer_staples'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('vegetables', '🥕 Fruit & vegetables'), ('fish', '🐟 Fish'), ('meat', '🥩 Meat'), ('vegetarian', '🌱 Vegetarian protein'), ('dairy', '🧀 Dairy & eggs'), ('bakery', '🍞 Bread & bakery'), ('breakfast', '🥣 Breakfast & snacks'), ('pantry', '🫙 Pantry'), ('frozen', '❄️ Frozen'), ('speciality', '🥢 Asian / speciality shop'), ('other', '🛒 Other')], default='other', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recipeimport',
            name='plan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeimport',
            name='plan_next',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='recipeimport',
            name='plan_slot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='WeeklySkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(help_text='Monday of the week.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='meals.weeklyitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'week'), name='unique_skip_per_week')],
            },
        ),
    ]
