# Generated by Django 5.2.17 on 2026-10-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_weekly_items_and_planning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklySkip',
        ),
    ]
