# Generated by Django 5.2.17 on 2026-10-05 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

SCOPED = ["Dish", "PlannedMeal", "FamilyMember", "Rule", "ExtraItem", "ShoppingCheck", "MenuRequest",
          "RecipeImport", "RecipePhoto", "WeeklyItem"]


def to_first_household(apps, schema_editor):
    """Everything entered before there were households belongs to the family that used the app."""
    Household = apps.get_model("meals", "Household")
    scoped = [apps.get_model("meals", name) for name in SCOPED]
    if not Household.objects.exists() and not any(model.objects.exists() for model in scoped):
        return  # a new installation
    household = Household.objects.order_by("pk").first() or Household.objects.create()
    household.name = household.name or "Our family"
    household.ai_approved = True
    household.save()
    for model in scoped:
        model.objects.filter(household=None).update(household=household)


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_remove_weekly_skips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['name', 'pk']},
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcheck',
            name='unique_check_per_week',
        ),
        migrations.AddField(
            model_name='dish',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='extraitem',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='household',
            name='ai_approved',
            field=models.BooleanField(default=False, verbose_name='AI approved'),
        ),
        migrations.AddField(
            model_name='household',
            name='ai_daily_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Empty: the app's default. 0: no AI.", max_digits=6, null=True, verbose_name='AI limit per day (USD)'),
        ),
        migrations.AddField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='household',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Suspended households can't log in.", verbose_name='active'),
        ),
        migrations.AddField(
            model_name='household',
            name='name',
            field=models.CharField(blank=True, help_text='E.g. The Smiths.', max_length=100),
        ),
        migrations.AddField(
            model_name='menurequest',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='plannedmeal',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='recipeimport',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='recipephoto',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='rule',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='shoppingcheck',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AddField(
            model_name='weeklyitem',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.household'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_dish_per_household'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcheck',
            constraint=models.UniqueConstraint(fields=('household', 'week', 'key'), name='unique_check_per_week'),
        ),
        migrations.RunPython(to_first_household, migrations.RunPython.noop),
    ]
