# Generated by Django 5.2.17 on 2026-10-05 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def from_earlier_requests(apps, schema_editor):
    """What menus and recipe imports cost before there was a ledger."""
    AIUsage = apps.get_model("meals", "AIUsage")
    for model_name, kind in [("MenuRequest", "menu"), ("RecipeImport", "recipe")]:
        for job in apps.get_model("meals", model_name).objects.exclude(cost=None, input_tokens=0):
            AIUsage.objects.create(
                household_id=job.household_id, user_id=job.created_by_id, kind=kind, model=job.model,
                input_tokens=job.input_tokens, output_tokens=job.output_tokens, web_searches=job.web_searches,
                cost=job.cost or 0, created_at=job.finished_at or job.created_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_household_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('menu', 'Menu'), ('recipe', 'Recipe')], max_length=10)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('web_searches', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='cost (USD)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to='meals.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI usage',
                'verbose_name_plural': 'AI usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(from_earlier_requests, migrations.RunPython.noop),
    ]
