# Generated by Django 5.2.17 on 2026-10-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0020_price_earlier_ai_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(help_text='Monday of the week.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='meals.weeklyitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'week'), name='unique_weekly_skip')],
            },
        ),
    ]
