from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "meals"

urlpatterns = [
    path("", views.home, name="home"),
    path("week/", views.menu, name="menu"),
    path("week/<str:day>/", views.menu, name="menu_of"),
    path("meal/new/", views.meal_edit, name="meal_new"),
    path("meal/<int:pk>/", views.meal_edit, name="meal"),
    path("meal/<int:pk>/feedback/", views.feedback, name="feedback"),
    path("meal/<int:pk>/replace/", views.meal_replace, name="meal_replace"),
    path("meal/<int:pk>/feedback/quick/", views.feedback_quick, name="feedback_quick"),
    path("shopping/", views.shopping, name="shopping"),
    path("shopping/<str:day>/", views.shopping, name="shopping_of"),
    path("shopping/<str:day>/state/", views.shopping_state, name="shopping_state"),
    path("shopping/<str:day>/toggle/", views.shopping_toggle, name="shopping_toggle"),
    path("shopping/<str:day>/extra/", views.extra_add, name="extra_add"),
    path("shopping/extra/<int:pk>/delete/", views.extra_delete, name="extra_delete"),
    path("shopping/extra/<int:pk>/restore/", views.extra_restore, name="extra_restore"),
    path("dish/<int:pk>/ingredients/", views.ingredients, name="ingredients"),
    path("recipes/", views.recipes, name="recipes"),
    path("recipes/add/", views.recipe_add, name="recipe_add"),
    path("recipes/link/", views.recipe_link_new, name="recipe_link_new"),
    path("recipes/new/", views.recipe_edit, name="recipe_new"),
    path("recipes/photo/", views.recipe_photo_new, name="recipe_photo_new"),
    path("recipes/photo/<int:pk>/", views.recipe_import_view, name="recipe_import"),
    path("recipes/photo/<int:pk>/retry/", views.recipe_import_retry, name="recipe_import_retry"),
    path("recipes/photo/<int:pk>/discard/", views.recipe_import_discard, name="recipe_import_discard"),
    path("recipes/photo/<int:pk>/status/", views.recipe_import_status, name="recipe_import_status"),
    path("photos/<int:pk>/", views.recipe_photo_file, name="photo"),
    path("photos/<int:pk>/delete/", views.recipe_photo_delete, name="photo_delete"),
    path("recipes/<int:pk>/photos/", views.recipe_photo_add, name="recipe_photo_add"),
    path("recipes/<int:pk>/", views.recipe, name="recipe"),
    path("recipes/<int:pk>/edit/", views.recipe_edit, name="recipe_edit"),
    path("recipes/<int:pk>/status/", views.recipe_status, name="recipe_status"),
    path("settings/", views.family, name="family"),
    # The settings page used to be the "Family" tab.
    path("family/", RedirectView.as_view(pattern_name="meals:family", permanent=True)),
    path("settings/member/new/", views.member_edit, name="member_new"),
    path("settings/member/<int:pk>/", views.member_edit, name="member"),
    path("settings/rule/<int:pk>/", views.rule_edit, name="rule"),
    path("settings/rule/<int:pk>/toggle/", views.rule_toggle, name="rule_toggle"),
    path("settings/household/", views.household_edit, name="household"),
    path("settings/staples/add/", views.staple_add, name="staple_add"),
    path("settings/weekly/add/", views.weekly_item_add, name="weekly_item_add"),
    path("settings/weekly/<int:pk>/delete/", views.weekly_item_delete, name="weekly_item_delete"),
    path("meal/pick/", views.meal_pick, name="meal_pick"),
    path("settings/staples/remove/", views.staple_remove, name="staple_remove"),
    path("settings/usual-week/", views.usual_week, name="usual_week"),
    path("week/<str:day>/create/", views.menu_create, name="menu_create"),
    path("week/<str:day>/copy/", views.menu_copy, name="menu_copy"),
    path("plan/<int:pk>/", views.menu_request, name="menu_request"),
    path("plan/<int:pk>/status/", views.menu_request_status, name="menu_request_status"),
]
