# Generated by Django 5.2.17 on 2026-10-05 07:55

import django.db.models.deletion
from django.db import migrations, models


def join_first_household(apps, schema_editor):
    """The people who used the app before households share the first one."""
    User = apps.get_model("accounts", "User")
    Household = apps.get_model("meals", "Household")
    users = User.objects.filter(household=None)
    if users.exists():
        household = Household.objects.order_by("pk").first() or Household.objects.create(name="Our family", ai_approved=True)
        users.update(household=household)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_login_code_requests'),
        ('meals', '0018_household_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='meals.household'),
        ),
        migrations.RunPython(join_first_household, migrations.RunPython.noop),
    ]
